name: hackyeah2
channels:
  - powerai
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.0.2
  - click=7.0
  - gym=0.15.3
  - mpi4py=3.0.3
  - nomkl=3.0
  - numpy=1.18.1
  - tabulate=0.8.3
  - tensorflow<=1.14
  - pip:
      - stable-baselines