MEAN_START_SKILL_LEVEL = 20
STD_START_SKILL_LEVEL = 10

POPULATION_MEAN_SKILL_GAIN = 2
POPULATION_STD_SKILL_GAIN = 1.8
POPULATION_STD_TYPE_GAIN = 0.01
POPULATION_MIN_SKILL_GAIN = 0.1

STUDENT_SKILL_GAIN_STD = 0.2

TEST_SCORE_STD = 0.5

TARGET_SCORE = 95

REVIEW_RATIO = 0.25

REWARD_FOR_ACHIEVING_TARGET_LEVEL = 100
REWARD_FOR_ACHIEVING_ALL_LEVELS = 1000

PENALTY_FOR_UNNECESSARY_TEST = -1000
TIME_PENALTY_FOR_TEST = - 2
GAIN_MULTIPLIER_FOR_TEST = 0

NOT_ADAPTED_DIFFICULTY_PENALTY = 0.25

TIME_PENALTY = -1
# GAIN_REWARD_RATIO = 0.1