MEAN_START_SKILL_LEVEL = 20
STD_START_SKILL_LEVEL = 10

POPULATION_MEAN_SKILL_GAIN = 1
POPULATION_STD_SKILL_GAIN = 0.2
POPULATION_STD_TYPE_GAIN = 0.01
POPULATION_MIN_SKILL_GAIN = 0.1

TALENTED_MEAN_SKILL_GAIN = 4
TALENTED_STD_SKILL_GAIN = 0.2
TALENTED_STD_TYPE_GAIN = 0.01
TALENTED_MIN_SKILL_GAIN = 3

STUDENT_SKILL_GAIN_STD = 0.2

TEST_SCORE_STD = 0.5

TARGET_SCORE = 95

REVIEW_RATIO = 0.25

REWARD_FOR_ACHIEVING_TARGET_LEVEL = 100
REWARD_FOR_ACHIEVING_ALL_LEVELS = 1000

PENALTY_FOR_UNNECESSARY_TEST = -1000
TIME_PENALTY_FOR_TEST = - 2
GAIN_MULTIPLIER_FOR_TEST = 1.2

NOT_ADAPTED_DIFFICULTY_PENALTY = 0.4

ADAPTED_TRAIN_TYPE_REWARD = 1

TIME_PENALTY = -2
# GAIN_REWARD_RATIO = 0.1